---
- name: SNS Message Sender
  hosts: all
  gather_facts: no
  connection: local

  vars:
    subject: "{{target_aem_stack_prefix}} - {{ message_type }}"

  tasks:
    - name: "Get facts for Target AEM Stack {{ target_aem_stack_prefix }}"
      ec2_instance_facts:
        filters:
          "tag:StackPrefix": "{{ target_aem_stack_prefix }}"
        region: "{{ aws.region }}"
      # To reduce the output of the playbook this outputs is suppress.
      # The value can be replaced with a debug true/false option in the future.
      no_log: False
      register: target_aem_stack_exists

    - name: "Check if Target AEM Stack {{ target_aem_stack_prefix }} exist."
      fail:
        msg: "Error: Target AEM Stack '{{ target_aem_stack_prefix }}' does not exists."
      when: target_aem_stack_exists.instances is defined and target_aem_stack_exists.instances[0] is undefined

    - set_fact:
        main_stack_name: "{{ stack_prefix }}-{{ main.stack_name }}"

    - name: "{{ subject }}: Retrieve Main Stack CloudFormation resources facts"
      cloudformation_facts:
        stack_name: "{{ main_stack_name }}"
        region: "{{ aws.region }}"
      register: main_stack_facts

    - set_fact:
        stack_manager_stack_arn: "{{ main_stack_facts.ansible_facts.cloudformation[main_stack_name].stack_outputs.StackManagerStackArn }}"

    - set_fact:
        stack_manager_stack_name: "{{ stack_manager_stack_arn.split('/')[1] }}"

    - name: "{{ subject }}: Retrieve Stack Manager CloudFormation resources facts"
      cloudformation_facts:
        stack_name: "{{ stack_manager_stack_name }}"
        region: "{{ aws.region }}"
      register: stack_manager_stack_facts

    - set_fact:
        stack_manager_stack_outputs: "{{ stack_manager_stack_facts.ansible_facts.cloudformation[stack_manager_stack_name].stack_outputs }}"
        s3_bucket: "{{ stack_manager_stack_facts.ansible_facts.cloudformation[stack_manager_stack_name].stack_parameters.DataBucketNameParameter }}"

    - set_fact:
        dynamodb_tablename: "{{ stack_manager_stack_outputs.AemStackManagerTableName }}"
        sns_topic: "{{ stack_manager_stack_outputs.StackManagerTopicArn }}"
        externalId: "{{ 9999999999999999999999 | random | to_uuid }}"

    - name: "Generating message file"
      template:
        src: "../../../templates/sns/{{ message_type }}.json"
        dest: "../../../stage/{{ message_type }}.json"
        force: true

    - name: "Load generated message payload file"
      set_fact:
        message: "{{ lookup('file', '../../../stage/{{ message_type }}.json') }}"

    - debug:
        msg: "Send message: {{ message }}, with subject: {{ subject }}, to topic: {{ sns_topic }}, in region: {{ aws.region }}"

    - name: "{{ subject }}: Send message to SNS Topic"
      sns:
        msg: "{{ message }}"
        subject: "{{ subject }}"
        topic: "{{ sns_topic }}"
        region: "{{ aws.region }}"

    - name: "{{ subject }}: Poll to check if command was executed"
      dynamodb_search:
        table_name: "{{ dynamodb_tablename }}"
        attribute: externalId
        attribute_value: "{{ externalId }}"
        get_attribute: state
        select: SPECIFIC_ATTRIBUTES
        comparisonoperator: EQ
        state: scan
        region: "{{ aws.region }}"
      register: dbscan
      until: dbscan.item != [] and dbscan.item[0].state.S in ["Success", "Failed"]
      retries: "{{ poll_timeout.check_command_execution.retries }}"
      delay: "{{ poll_timeout.check_command_execution.delay }}"

    - set_fact:
        cmd_state: "{{ item.state.S }}"
      with_items:
        "{{ dbscan.item }}"

    - name: "{{ subject }}: Check if command failed"
      set_fact:
        general_error: 1
      when: cmd_state == "Failed"

    - name: "{{ subject }}: Query for command id"
      dynamodb_search:
        table_name: "{{ dynamodb_tablename }}"
        attribute: externalId
        attribute_value: "{{ externalId }}"
        get_attribute: command_id
        select: SPECIFIC_ATTRIBUTES
        comparisonoperator: EQ
        state: scan
        region: "{{ aws.region }}"
      register: dbscan

    - set_fact:
        cmd_id: "{{ item.command_id.S }}"
      with_items:
        "{{ dbscan.item }}"
      when: dbscan is defined and dbscan.item is defined

    - fail:
        msg: "Lambda function execution failed. Check Cloudwatch Logfiles for detail information"
      when: general_error is defined and cmd_id is undefined

    - name: "{{ subject }}: Get path to log files"
      aws_s3:
        mode: list
        bucket: "{{ s3_bucket }}"
        prefix: "{{ stack_prefix }}/stack-manager/SSMOutput/{{ cmd_id }}"
      register: output_files

    - name: "{{ subject }}: Set facts for getting command output"
      set_fact:
        log_path: "{{ playbook_dir }}/../../logs/"
        dl_path: "{{ stack_prefix }}/stack-manager/SSMOutput/{{ cmd_id }}"
        s3_files: "{{ output_files.s3_keys }}"
      when: cmd_id is defined

    - name: "{{ subject }}: Create Download directory in {{log_path }}/{{ dl_path }}"
      file:
        path: "{{ log_path }}/{{ item|regex_replace('(stdout|stderr)$', '') }}"
        state: directory
      with_items:
        - "{{ s3_files }}"
      when: general_error is defined or show_log_on_failure_only == false

    - name: "{{ subject }}: Save log files"
      aws_s3:
        mode: get
        bucket: "{{ s3_bucket }}"
        object: "{{ item }}"
        dest: "{{ log_path }}{{ item }}"
      with_items:
        - "{{ s3_files }}"
      register: saved_files
      when: general_error is defined or show_log_on_failure_only == false

    - name: "{{ subject }}: Find non-error log files"
      find:
        paths: "{{log_path }}{{ dl_path }}"
        file_type: file
        patterns: stdout
        recurse: yes
      register: stdout_files
      when: show_log_on_failure_only == false

    - name: "{{ subject }}: Show non-error log files content"
      log_output:
        type: file
        log_files: "{{ stdout_files.files | map(attribute='path')|list }}"
      when: show_log_on_failure_only == false

    - name: "{{ subject }}: Find error log files"
      find:
        paths: "{{log_path }}{{ dl_path }}"
        file_type: file
        patterns: stderr
        recurse: yes
      register: stderr_files
      when: general_error is defined

    - name: "{{ subject }}: Show error log files content"
      log_output:
        type: file
        log_files: "{{ stderr_files.files | map(attribute='path')|list }}"
      when: general_error is defined

    - fail:
        msg: "Error: Failed executing event {{ message_type }}"
      when: general_error is defined

    - name: Remove generated message payload file
      file:
        path: "../../../stage/{{ message_type }}.json"
        state: absent
